#!/usr/bin/env bash
sh $HOME/scripts/Minecraft-Scripts/symlinks-Prismlauncher-saves.sh &
sh $HOME/scripts/Minecraft-Scripts/symlinks-Prismlauncher-screenshots.sh &
sh $HOME/scripts/Minecraft-Scripts/symlinks-Prismlauncher-shaders.sh &
sh $HOME/scripts/Minecraft-Scripts/symlinks-Prismlauncher-texturepack.sh 
